### ISSUE TITLE
Feature request: exclusive numa region access

### ISSUE THREAD

**Issue by ghost** [mjasny/expinfo#5]
It would be great to request exclusive access to a numa region. This would allow experiments that run only on one numa region to run concurrently without affecting each other. Ideally, the run_exp script could also set the required environment variables such that the script automatically runs within the requested region.

**Comment by mjasny** [comment]
Do you mean setting the environment variables via `numactl --membind` or something else?

**Comment by ghost** [comment]
Yes, these are the parameters I had in mind. And it would be great if the exclusive locking could also be on the granularity of numa nodes or the entire node.

**Comment by mjasny** [comment]
implemented in aecf0342368b7726c96d54b47ca315921f319eb6
